[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "C en Resumen"
authors = [{name = "Santiago Tapia-Fernández", email = "santiago.tapia@upm.es"}]
dynamic = ["version", "description"]
